### ISSUE TITLE
Ubuntu 16.04 scrape.js giving error at pm2 other are online

### ISSUE THREAD

**Issue by scriptzteam** [AlphaReign/scraper#1]
scrape show as errored other are online

```
root@GBiT:/home/data# pm2 show 1
 Describing process with id 1 - name scrape
┌───────────────────┬────────────────────────────────────┐
│ status            │ errored                            │
│ name              │ scrape                             │
│ restarts          │ 120                                │
│ uptime            │ 0                                  │
│ script path       │ /home/scriptz/scraper/scrape.js    │
│ script args       │ N/A                                │
│ error log path    │ /root/.pm2/logs/scrape-error-1.log │
│ out log path      │ /root/.pm2/logs/scrape-out-1.log   │
│ pid path          │ /root/.pm2/pids/scrape-1.pid       │
│ interpreter       │ node                               │
│ interpreter args  │ N/A                                │
│ script id         │ 1                                  │
│ exec cwd          │ /home/scriptz/scraper              │
│ exec mode         │ fork_mode                          │
│ node.js version   │ 4.2.6                              │
│ watch & reload    │ ✘                                  │
│ unstable restarts │ 0                                  │
│ created at        │ N/A                                │
└───────────────────┴────────────────────────────────────┘
 Revision control metadata
┌──────────────────┬───────────────────────────────────────────┐
│ revision control │ git                                       │
│ remote url       │ https://github.com/AlphaReign/scraper.git │
│ repository root  │ /home/scriptz/scraper                     │
│ last update      │ 2017-03-03T11:30:43.665Z                  │
│ revision         │ 4dade970956f0bb280a773acda6bd5d47ef3ccbf  │
│ comment          │ update readme                             │
│ branch           │ master                                    │
└──────────────────┴───────────────────────────────────────────┘
 Add your own code metrics: http://bit.ly/code-metrics
 Use `pm2 logs scrape [--lines 1000]` to display logs
 Use `pm2 monit` to monitor CPU and Memory usage scrape
```

`TypeError: this is not a typed array.
    at Function.from (native)
    at Object.<anonymous> (/home/scriptz/scraper/node_modules/ws/lib/PerMessageDeflate.js:8:24)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/scriptz/scraper/node_modules/ws/lib/WebSocket.js:16:27)
    at Module._compile (module.js:410:26)
TypeError: this is not a typed array.
    at Function.from (native)
    at Object.<anonymous> (/home/scriptz/scraper/node_modules/ws/lib/PerMessageDeflate.js:8:24)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/scriptz/scraper/node_modules/ws/lib/WebSocket.js:16:27)
    at Module._compile (module.js:410:26)
TypeError: this is not a typed array.
    at Function.from (native)
    at Object.<anonymous> (/home/scriptz/scraper/node_modules/ws/lib/PerMessageDeflate.js:8:24)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/scriptz/scraper/node_modules/ws/lib/WebSocket.js:16:27)
    at Module._compile (module.js:410:26)
TypeError: this is not a typed array.
    at Function.from (native)
    at Object.<anonymous> (/home/scriptz/scraper/node_modules/ws/lib/PerMessageDeflate.js:8:24)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/scriptz/scraper/node_modules/ws/lib/WebSocket.js:16:27)
    at Module._compile (module.js:410:26)
`

**Comment by Raxvis** [comment]
Upgrade node past 4.5.0

https://stackoverflow.com/a/42331959/1718732

**Comment by scriptzteam** [comment]
Thn just did this and testing:

```
sudo npm cache clean -f
sudo npm install -g n
sudo n 4.5.0

export N_PREFIX=; n 4.5.0

node -v
4.5.0
```

**Comment by scriptzteam** [comment]
More errors Trace: [cluster_block_exception] blocked by: [SERVICE_UNAVAILABLE/1/state not recovered / initialized];...

```
netstat -tulpen
tcp6       0      0 192.168.0.52:9200       :::*                    LISTEN      115        23036       1361/java
tcp6       0      0 192.168.0.52:9300       :::*                    LISTEN      115        23009       1361/java
```

```
root@GBiT:~/.pm2/logs# tail -f scrape-error-1.log
    at flush (/home/scriptz/scraper/node_modules/asap/raw.js:50:29)
    at nextTickCallbackWith0Args (node.js:420:9)
    at process._tickDomainCallback [as _tickCallback] (node.js:390:13)
Trace: [cluster_block_exception] blocked by: [SERVICE_UNAVAILABLE/1/state not recovered / initialized];
    at /home/scriptz/scraper/scrape.js:34:17
    at tryCallOne (/home/scriptz/scraper/node_modules/promise/lib/core.js:37:12)
    at /home/scriptz/scraper/node_modules/promise/lib/core.js:123:15
    at flush (/home/scriptz/scraper/node_modules/asap/raw.js:50:29)
    at nextTickCallbackWith0Args (node.js:420:9)
    at process._tickDomainCallback [as _tickCallback] (node.js:390:13)
Trace: [cluster_block_exception] blocked by: [SERVICE_UNAVAILABLE/1/state not recovered / initialized];
    at /home/scriptz/scraper/scrape.js:34:17
    at tryCallOne (/home/scriptz/scraper/node_modules/promise/lib/core.js:37:12)
    at /home/scriptz/scraper/node_modules/promise/lib/core.js:123:15
    at flush (/home/scriptz/scraper/node_modules/asap/raw.js:50:29)
    at nextTickCallbackWith0Args (node.js:420:9)
    at process._tickDomainCallback [as _tickCallback] (node.js:390:13)

var es = new elasticsearch.Client({host: '192.168.0.52:9200'});
```

**Comment by Raxvis** [comment]
Trying doing a "service elasticsearch status" or equivalent.  It looks like ElasticSearch is down

**Comment by Raxvis** [comment]
Any follow up on this?
