### ISSUE TITLE
Unable to run categorize.js

### ISSUE THREAD

**Issue by deafboy** [AlphaReign/scraper#3]
categorize.js is failing with these errors in the log:

`Trace: [query_shard_exception] No mapping found for [categories_updated] in order to sort on, with { index_uuid=u1AEawX_QOioGgz2GNxtAw index=torrents }
    at /opt/scraper/categorize.js:37:17
    at tryCallOne (/opt/scraper/node_modules/promise/lib/core.js:37:12)
    at /opt/scraper/node_modules/promise/lib/core.js:123:15
    at flush (/opt/scraper/node_modules/asap/raw.js:50:29)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickDomainCallback [as _tickCallback] (internal/process/next_tick.js:128:9)
`

elasticsearch.log:

`[2017-03-08T08:02:00,082][DEBUG][o.e.a.s.TransportSearchAction] [jEj0gP0] All shards failed for phase: [query]
org.elasticsearch.transport.RemoteTransportException: [jEj0gP0][127.0.0.1:9300][indices:data/read/search[phase/query]]
Caused by: org.elasticsearch.index.query.QueryShardException: No mapping found for [categories_updated] in order to sort on
        at org.elasticsearch.search.sort.FieldSortBuilder.build(FieldSortBuilder.java:262) ~[elasticsearch-5.2.2.jar:5.2.2]
        at org.elasticsearch.search.sort.SortBuilder.buildSort(SortBuilder.java:156) ~[elasticsearch-5.2.2.jar:5.2.2]
        at org.elasticsearch.search.SearchService.parseSource(SearchService.java:688) ~[elasticsearch-5.2.2.jar:5.2.2]
        at org.elasticsearch.search.SearchService.createContext(SearchService.java:540) ~[elasticsearch-5.2.2.jar:5.2.2]
        at org.elasticsearch.search.SearchService.createAndPutContext(SearchService.java:516) ~[elasticsearch-5.2.2.jar:5.2.2]
        at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:251) ~[elasticsearch-5.2.2.jar:5.2.2]
        at org.elasticsearch.action.search.SearchTransportService$6.messageReceived(SearchTransportService.java:298) ~[elasticsearch-5.2.2.jar:5.2.2]
        at org.elasticsearch.action.search.SearchTransportService$6.messageReceived(SearchTransportService.java:295) ~[elasticsearch-5.2.2.jar:5.2.2]
        at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:69) ~[elasticsearch-5.2.2.jar:5.2.2]
        at org.elasticsearch.transport.TransportService$7.doRun(TransportService.java:610) [elasticsearch-5.2.2.jar:5.2.2]
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:596) [elasticsearch-5.2.2.jar:5.2.2]
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-5.2.2.jar:5.2.2]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_121]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_121]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
`

**Comment by Raxvis** [comment]
So the mapping doesn't exist for categories_updated in the index.

Commit df9aca003f9594171e8bb0286eb4435e79ff9199 should fix this by running a script that sets the value to 0 if the key doesn't exist.  You can also update the mapping if need be to include categories_updated if you know how to do that.  https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-put-mapping.html
