### ISSUE TITLE
Error with scrape.js

### ISSUE THREAD

**Issue by peva3** [AlphaReign/scraper#6]
Trace: [index_not_found_exception] no such index, with { resource.type=index_or_alias resource.id=torrents index=torrents }
    at /opt/scraper/scrape.js:34:17
    at tryCallOne (/opt/scraper/node_modules/promise/lib/core.js:37:12)
    at /opt/scraper/node_modules/promise/lib/core.js:123:15
    at flush (/opt/scraper/node_modules/asap/raw.js:50:29)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickDomainCallback (internal/process/next_tick.js:128:9)

Any ideas? Thanks

**Comment by peva3** [comment]
Nevermind fixed it.

**Comment by Raxvis** [comment]
What was the issue?  I assumed that the index wasn't created yet

**Comment by peva3** [comment]
Going to close this, it got resolved on the other repo
