### ISSUE TITLE
Elastic Issue

### ISSUE THREAD

**Issue by ghost** [AlphaReign/scraper#9]
Hello. i read you will close any issues about webserver and setup. but im just having a issue with the scraper . the log is showing this error,. any help is much appreciated.

displayName: 'NotAcceptable',
  message: 'Content-Type header [application/x-ldjson] is not supported' }
Queuing: 8f229c0f84586da825a798e737ac0215b50cd9f1 | NASS224AVI
{ Error: Content-Type header [application/x-ldjson] is not supported
    at respond (/root/scraper/node_modules/elasticsearch/src/lib/transport.js:289:15)
    at checkRespForFailure (/root/scraper/node_modules/elasticsearch/src/lib/transport.js:248:7)
    at HttpConnector.<anonymous> (/root/scraper/node_modules/elasticsearch/src/lib/connectors/http.js:164:7)
    at IncomingMessage.wrapper (/root/scraper/node_modules/elasticsearch/node_modules/lodash/index.js:3095:19)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickDomainCallback (internal/process/next_tick.js:128:9)
  status: 406,

**Comment by Raxvis** [comment]
Need to upgrade elasticsearch.js npm module to match your elasticsearch version

See here: https://discuss.elastic.co/t/node-bulk-indexing-not-working-content-type-header-application-x-ldjson-is-not-supported/114944/7

**Comment by ghost** [comment]
Thanks for the reply mate will give it a go

**Comment by ghost** [comment]
Working now thanks for your quick response

**Comment by Raxvis** [comment]
Glad to hear
